# Generated by Django 5.1.6 on 2025-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
